# Lizenzportal Supabase – Projekt ojryoosqwfbzlmdeywzs
# Nur Update/Lizenz-API: npm run lp:deploy:mandanten-update (Repo-Root)
# Alle Functions: cd supabase-license-portal && supabase link --project-ref … && supabase functions deploy

[api]
enabled = true

[functions.license]
verify_jwt = false

[functions.limit-exceeded]
verify_jwt = false

[functions.update-impressum]
verify_jwt = false

[functions.trigger-mandanten-db-rollout]
verify_jwt = false

[functions.trigger-github-deploy]
verify_jwt = false

[functions.submit-beta-feedback]
verify_jwt = false
